config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :expenditures, :default_expenditures

  resources :secrets do
    collection do
      get 'add_new_value'
      get 'edit_value'

      post 'create_value'
      post 'update_value'
    end
  end

  get 'expenditure/month/:month(/year/:year)', to: 'expenditures#month_views', as: 'month_views', constraints: { month: /(?:[1-9]|[0][1-9]|[1][0-2])/, year: /[0-9]{4,}/ }
  get 'expenditure/year_glance/year/:year', to: 'expenditures#year_glance', as: 'year_glance', constraints: { year: /[0-9]{4,}/ }
  get 'manage_defaults', to: 'expenditures#manage_defaults', as: 'manage_defaults'
  get ':id/manage-values', to: 'secrets#manage_values', as: 'manage_values'

  root to: 'users#home'
end

app/models/default_expenditure.rb
# == Schema Information
#
# Table name: default_expenditures
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_default_expenditures_on_user_id  (user_id)
#

# :nodoc:
class DefaultExpenditure < ActiveRecord::Base
  has_many :expenditures
  belongs_to :user

  scope :by_users, ->(user_ids) { where('user_id in (?)', user_ids) }

  def self.for_current_user(user)
    by_users([0, user.id])
  end

  def editable?(user)
    user_id == user.id
  end
end

app/controllers/default_expenditures_controller.rb
# :nodoc:
class DefaultExpendituresController < ApplicationController
  before_action :find_default_expenditure,
                only: [:edit, :update].freeze
  before_action :editable?,
                only: [:edit, :update].freeze

  def index
    @default_expenditures = DefaultExpenditure
                            .for_current_user(current_user)
                            .order(:user_id, :name)
  end

  def new
    @default_expenditure = current_user.default_expenditures.new
  end

  def create
    @default_expenditure = current_user
                           .default_expenditures
                           .new(default_expenditure_params)
    if @default_expenditure.save
      redirect_to default_expenditures_path, notice: 'Type added successfully'
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @default_expenditure.update_attributes(default_expenditure_params)
      redirect_to default_expenditures_path, notice: 'Type altered successfully'
    else
      render action: :edit
    end
  end

  private

  def default_expenditure_params
    params.require(:default_expenditure).permit(:name)
  end

  def find_default_expenditure
    @default_expenditure = current_user.default_expenditures.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to default_expenditures_path,
                alert: 'You don\'t have sufficient privileges to edit this type'
  end

  def editable?
    unless @default_expenditure.editable?(current_user)
      alert_message = 'You don\'t have sufficient privileges to edit this type'
      redirect_to default_expenditures_path,
                  alert: alert_message
    end
  end
end

app/helpers/default_expenditures_helper.rb
# :nodoc:
module DefaultExpendituresHelper
end

app/views/default_expenditures/_default_expenditure.slim
li.list-group-item
  - if default_expenditure.editable?(current_user)
    = link_to default_expenditure.name, edit_default_expenditure_path(default_expenditure)
  - else
    = default_expenditure.name

app/views/default_expenditures/_form.slim
.row
  .col-lg-6

    = form_for(@default_expenditure, { class: '' }) do |e|

      = render partial: 'common/form_validation_message', locals: { obj: @default_expenditure }

      .form-group
        label Name
        = e.text_field(:name, { class: 'form-control' })

      = e.submit({ class: 'btn btn-info' })
      |&nbsp;&nbsp;
      = link_to 'Cancel', default_expenditures_path, { class: 'btn btn-danger' }

app/views/default_expenditures/_menu.slim
.row
  = menu_group pull: :right do
    = link_to 'New', new_default_expenditure_path, { class: 'btn btn-info' }
br

app/views/default_expenditures/edit.slim
h3 Edit Type
= render 'form'

app/views/default_expenditures/index.slim
h3 Defaults

= render 'menu'

ul.list-group
  = render @default_expenditures

= render 'menu'

app/views/default_expenditures/new.slim
h3 Add Type
= render 'form'