config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :expenditures, :default_expenditures

  resources :secrets do
    collection do
      get 'add_new_value'
      get 'edit_value'

      post 'create_value'
      post 'update_value'
    end
  end

  get 'expenditure/month/:month(/year/:year)', to: 'expenditures#month_views', as: 'month_views', constraints: { month: /(?:[1-9]|[0][1-9]|[1][0-2])/, year: /[0-9]{4,}/ }
  get 'expenditure/year_glance/year/:year', to: 'expenditures#year_glance', as: 'year_glance', constraints: { year: /[0-9]{4,}/ }
  get 'manage_defaults', to: 'expenditures#manage_defaults', as: 'manage_defaults'
  get ':id/manage-values', to: 'secrets#manage_values', as: 'manage_values'

  root to: 'users#home'
end

app/models/secret.rb
# == Schema Information
#
# Table name: secrets
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  name                :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  secret_values_count :integer          default(0)
#
# Indexes
#
#  index_secrets_on_user_id  (user_id)
#

# :nodoc:
class Secret < ActiveRecord::Base
  has_many :secret_values, dependent: :destroy

  belongs_to :user

  validates :name, presence: :true
end

app/controllers/secrets_controller.rb
# :nodoc:
class SecretsController < ApplicationController
  before_action :set_secret, only: [:edit,
                                    :update,
                                    :manage_values,
                                    :add_new_value,
                                    :create_value,
                                    :update_value
  ].freeze

  def index
    @secrets = current_user.secrets
  end

  def new
    @secret = current_user.secrets.new
  end

  def create
    @secret = current_user.secrets.new(secret_params)
    if @secret.save
      redirect_to secrets_path, notice: 'Secret added successfully'
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @secret.update_attributes(secret_params)
      redirect_to secrets_path, notice: 'Secret altered successfully'
    else
      render action: :edit
    end
  end

  def manage_values
  end

  def add_new_value
    @secret_value = @secret.secret_values.new
    render layout: false
  end

  def create_value
    @secret_value = @secret.secret_values.new(secret_value_params)
    if @secret_value.save
      render partial: 'secret_value',
             locals: { secret_value: @secret_value },
             status: :created
    else
      render nothing: true, status: :internal_server_error
    end
  end

  def update_value
  end

  private

  def secret_params
    params.require(:secret).permit(:name)
  end

  def secret_value_params
    params.require(:secret).permit(:key, :value)
  end

  def set_secret
    @secret = current_user.secrets.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    alert_msg = "Couldn't find any valid secrets for you.  Please try again."
    redirect_to secrets_path, alert: alert_msg
  end
end

app/helpers/secrets_helper.rb
# :nodoc:
module SecretsHelper
end

app/views/secrets/_controls.slim
.col-lg-4
  .list-btn
    = link_to 'Add New', 'javascript:void(0)', { class: 'btn btn-success', id: 'secrets_add_new_value', data: { secret: @secret.id } }
  .list-btn
    = link_to 'Save', 'javascript:void(0)', { class: 'btn btn-info', id: 'secrets_save_value', disabled: true }
  .list-btn
    = link_to 'Cancel', 'javascript:void(0)', { class: 'btn btn-danger', disabled: true, id: 'secrets_cancel' }
  .list-btn
    = link_to 'Back', secrets_path, { class: 'btn btn-danger' }

app/views/secrets/_form.slim
.row
  .col-lg-6

    = form_for(@secret, { html: { class: '', id: '' } }) do |e|

      = render partial: 'common/form_validation_message', locals: { obj: @secret }

      .form-group
        label Name
        = e.text_field(:name, { class: 'form-control', required: true, placeholder: 'Name', data: { required: 'value' } })

      = e.submit({ class: 'btn btn-info' })
      |&nbsp;&nbsp;
      = link_to 'Cancel', secrets_path, { class: 'btn btn-danger' }

app/views/secrets/_secret_value.slim
tr
  td = secret_value.key
  td = secret_value.value

app/views/secrets/_secret_values.slim
.col-lg-6
  table#secret_values.table.table-bordered.table-responsive.table-striped
    thead.bg-success
      th.col-md-6 Key
      th.col-md-6 Value
    tbody
      = render partial: 'secret_value', collection: @secret.secret_values

app/views/secrets/_value_form.slim
tr.active
	td
      = hidden_field_tag 'secret_id', @secret.id
      = text_field_tag(:secret_key, @secret_value.key, { placeholder: 'Key', class: 'form-control' })
	td = text_field_tag(:secret_value, @secret_value.value, { placeholder: 'Value', class: 'form-control' })

app/views/secrets/add_new_value.slim
= render 'value_form'

app/views/secrets/edit.slim
h2 Edit Secret
= render 'form'

app/views/secrets/index.slim
h2 My Secrets
br
.row
  = menu_group pull: :right do
    = link_to 'New', new_secret_path, {class: 'btn btn-info'}

.row
  ul.list-group.col-lg-6
    - @secrets.each do |secret|
      li.list-group-item
        span.badge = link_to secret.secret_values_count, manage_values_path(secret), { class: 'badge-link' }
        = link_to secret.name, edit_secret_path(secret)

br
.row
  = menu_group pull: :right do
    = link_to 'New', new_secret_path, {class: 'btn btn-info'}

app/views/secrets/manage_values.slim
h3 = @secret.name
= render 'secret_values'
= render 'controls'

app/views/secrets/new.slim
h2 New Secret
= render 'form'