config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :expenditures, :default_expenditures

  resources :secrets do
    collection do
      get 'add_new_value'
      get 'edit_value'

      post 'create_value'
      post 'update_value'
    end
  end

  get 'expenditure/month/:month(/year/:year)', to: 'expenditures#month_views', as: 'month_views', constraints: { month: /(?:[1-9]|[0][1-9]|[1][0-2])/, year: /[0-9]{4,}/ }
  get 'expenditure/year_glance/year/:year', to: 'expenditures#year_glance', as: 'year_glance', constraints: { year: /[0-9]{4,}/ }
  get 'manage_defaults', to: 'expenditures#manage_defaults', as: 'manage_defaults'
  get ':id/manage-values', to: 'secrets#manage_values', as: 'manage_values'

  root to: 'users#home'
end

app/models/expenditure.rb
# == Schema Information
#
# Table name: expenditures
#
#  id                     :integer          not null, primary key
#  name                   :string
#  amount                 :float
#  description            :text
#  date                   :datetime
#  user_id                :integer
#  created_by_id          :integer
#  updated_by_id          :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  default_expenditure_id :integer
#
# Indexes
#
#  index_expenditures_on_amount                  (amount)
#  index_expenditures_on_default_expenditure_id  (default_expenditure_id)
#  index_expenditures_on_user_id                 (user_id)
#

# :nodoc:
class Expenditure < ActiveRecord::Base
  def initialize(attributes = nil, options = {})
    super(attributes, options)
    self.date ||= Date.today
  end

  belongs_to :default_expenditure
  belongs_to :user

  validates :name, :date, presence: true
  validates :default_expenditure_id,
            presence: { message: "Type can't be blank" }
  validates :amount,
            presence: true,
            format: { with: /\A(?:[0-9])+(?:\.[0-9]{1,2}){0,1}\z/ }

  # Expenditure for specified date range
  # @param from [Date]
  # @param to [Date]
  # @return [Expenditure]
  scope :between, ->(from, to) { where(date: from..to) }

  # Expenditure for current month and year
  # @return [Expenditure]
  def self.for_current_month
    today = Time.zone.now
    between(today.beginning_of_month, today.end_of_month)
  end

  # Expenditures for selected month and year
  # @param month [Integer] the month needs to be selected
  # @param year [Integer] which year the month needs to be selected
  # @return [Expenditure]
  def self.for_selected_month(month, year)
    selected_date = Date.new(year.to_i, month.to_i).to_datetime.in_time_zone
    between(selected_date.beginning_of_month, selected_date.end_of_month)
  end
end

app/controllers/expenditures_controller.rb
# @author Selva Chezhian
class ExpendituresController < ApplicationController
  # @!group Callbacks

  before_action :check_month_views_params, only: :month_views

  # @!endgroup

  def index
    @expenditures = current_user
                    .expenditures
                    .includes(:default_expenditure)
                    .for_current_month
                    .order(:date, :name, :amount)
  end

  def new
    @expenditure = current_user.expenditures.new
  end

  def create
    @expenditure = current_user.expenditures.new(expenditure_params)
    if @expenditure.save
      redirect_to expenditures_path, notice: 'Expenditure added successfully'
    else
      render action: :new
    end
  end

  def edit
    @expenditure = current_user.expenditures.find(params[:id])
  end

  def update
    @expenditure = current_user.expenditures.find(params[:id])
    if @expenditure.update_attributes(expenditure_params)
      redirect_to expenditures_path, notice: 'Expenditure altered successfully'
    else
      render action: :edit
    end
  end

  def destroy
    @expenditure = current_user.expenditures.find(params[:id])
    @expenditure.destroy

    redirect_to expenditures_path, notice: 'Expenditure removed successfully'
  end

  def month_views
    @expenditures = current_user
                    .expenditures
                    .includes(:default_expenditure)
                    .for_selected_month(params[:month],
                                        params[:year])
                    .order(:date, :name, :amount)
  end

  def year_glance
  end

  def manage_defaults
    @defaults = DefaultExpenditure
                .for_current_user(current_user)
                .order(:user_id, :name)
  end

  private

  def expenditure_params
    params.require(:expenditure).permit(:name,
                                        :date,
                                        :amount,
                                        :default_expenditure_id)
  end

  def check_month_views_params
    if params[:month].starts_with?('0')
      redirect_to month_views_path(month: params[:month].slice(1),
                                   year: (params[:year] || Time.zone.now.year)),
                  status: :moved_permanently
    end
  end
end

app/views/expenditures/_current_month_expenditure.slim
h3 = "Expenditure for the month of #{ Time.zone.now.strftime('%B - %Y') }"

.row.current-month-header
  = menu_group do
    h4
      span.label.label-warning
        | Total Amount&nbsp;
        = number_to_currency(@expenditures.sum(:amount), locale: :ta)
  = menu_group pull: :right do
    = link_to 'Add', new_expenditure_path, { class: 'btn btn-info' }

table.table.table-responsive.table-striped.table-bordered.table-hover
  thead
    tr.success
      th Sl.No
      th Date
      th Name
      th Type
      th Amount
  tbody
    = render @expenditures

.row.current-month-header
  = menu_group pull: :right do
    = link_to 'Add', new_expenditure_path, { class: 'btn btn-info' }

javascript:
  counter = 1;
  while(counter <= 31) {
    $('.row-' + counter + ':last').css({ 'border-bottom': '2px solid #DA4EEA' });
    counter = counter + 1;
  }

app/views/expenditures/_expenditure.slim
tr class="row-#{expenditure.date.day}"
  td = expenditure_counter + 1
  td = expenditure.date.strftime('%d %B, %Y - %A')
  td
    = expenditure.name
    span.edit-image
      = link_to(edit_expenditure_path(expenditure)) do
        = image_tag('edit.png', title: 'Edit')

      = link_to(expenditure, { method: :delete, data: { confirm: 'Are you sure to remove this expenditure?' } }) do
        = image_tag('delete.png', size: '16x16', title: 'Delete')
  td = expenditure.default_expenditure.try(:name)
  td.price = number_to_currency(expenditure.amount, locale: :ta)

app/views/expenditures/_form.slim
.row
  .col-lg-6

    = form_for(@expenditure, { html: { class: '', id: 'expenditureForm' } }) do |e|

      = render partial: 'common/form_validation_message', locals: { obj: @expenditure }

      .form-group
        label Date
        = e.text_field(:date, {class: 'form-control datepicker', value: @expenditure.date.try(:strftime, '%d/%m/%Y'), readonly: true, required: true})

      .form-group
        label Name
        = e.text_field(:name, { class: 'form-control', required: true, placeholder: 'Name', data: { required: 'value' } })

      .form-group
        label Amount
        = e.number_field(:amount, { class: 'form-control', required: true })

      .form-group
        label Type
        = e.collection_select(:default_expenditure_id, DefaultExpenditure.for_current_user(current_user).order(:name, :user_id), :id, :name, { include_blank: 'Select Type' }, { class: 'form-control', required: true })


      = e.submit({ class: 'btn btn-info' })
      |&nbsp;&nbsp;
      = link_to 'Cancel', expenditures_path, { class: 'btn btn-danger' }

    javascript:
      $("#expenditureForm").validate({
        rules: {
          'expenditure[name]': 'required',
          'expenditure[amount]': {
            required: true,
            number: true,
            min: 0
          },
          'expenditure[default_expenditure_id]': 'required'
        },
        messages: {
          'expenditure[name]': "Expenditure Name can't be blank",
          'expenditure[amount]': {
            required: "Amount can't be blank",
            number: 'Amount should be number',
            min: 'Amount should be positive'
          },
          'expenditure[default_expenditure_id]': "Expenditure type can't be blank"
        }
      });

app/views/expenditures/edit.slim
h2 Edit Expenditure
br
= render 'form'

app/views/expenditures/index.slim
= render 'current_month_expenditure'

app/views/expenditures/manage_defaults.slim
h3 Defaults

= render 'menu'

ul.list-group
  = render @defaults

= render 'menu'

app/views/expenditures/month_views.slim
.row
  .col-lg-4.col-lg-4-offset
  .col-lg-4
    = select_month(params[:month].to_i, {}, { class: 'form-control month-year-select' })
    = select_year(params[:year].to_i, {}, { class: 'form-control month-year-select' })
    = link_to('Get Expenditure', {}, { class: 'btn btn-info', id: 'get_expenditure', href: 'javascript:void(0)' })
  .col-lg-4.col-lg-4-offset

h3 = "Expenditure for the month of #{ Date.new(params[:year].to_i, params[:month].to_i).strftime('%B - %Y') }"
h4
  span.label.label-warning
    | Total Amount&nbsp;
    = number_to_currency(@expenditures.sum(:amount), locale: :ta)

table.table.table-responsive.table-striped.table-bordered.table-hover
  thead
    tr.success
      th Sl.No
      th Date
      th Name
      th Type
      th Amount
  tbody
    = render @expenditures

javascript:
  counter = 1;
  while(counter <= 31) {
    $('.row-' + counter + ':last').css({ 'border-bottom': '2px solid #DA4EEA' });
    counter = counter + 1;
  }

app/views/expenditures/new.slim
h2 Add Expenditure
br
= render 'form'

app/views/expenditures/year_glance.slim
.row
  .col-lg-4.col-lg-4-offset
  .col-lg-4
    = select_year(params[:year].to_i, {}, { class: 'form-control month-year-select' })
    = link_to('Get Glance', {}, { class: 'btn btn-info', id: 'get_year_glance', href: 'javascript:void(0)' })
  .col-lg-4.col-lg-4-offset

h3 = "Expenditure Glance for the year #{ Date.new(params[:year].to_i).strftime('%Y') }"

table.table.table-responsive.table-striped.table-bordered.table-hover
  thead
    tr.success
      th Month
      th Amount
  tbody
    - (1..12).each do |month|
      - this_date = Date.new(params[:year].to_i, month)
      tr
        td = this_date.strftime('%B')
        td = number_to_currency(current_user.expenditures.for_selected_month(month, params[:year]).sum(:amount), locale: :ta)