config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :expenditures, :default_expenditures

  resources :secrets do
    collection do
      get 'add_new_value'
      get 'edit_value'

      post 'create_value'
      post 'update_value'
    end
  end

  get 'expenditure/month/:month(/year/:year)', to: 'expenditures#month_views', as: 'month_views', constraints: { month: /(?:[1-9]|[0][1-9]|[1][0-2])/, year: /[0-9]{4,}/ }
  get 'expenditure/year_glance/year/:year', to: 'expenditures#year_glance', as: 'year_glance', constraints: { year: /[0-9]{4,}/ }
  get 'manage_defaults', to: 'expenditures#manage_defaults', as: 'manage_defaults'
  get ':id/manage-values', to: 'secrets#manage_values', as: 'manage_values'

  root to: 'users#home'
end

app/views/common/_form_validation_message.slim
- obj.errors.any?
  .row
    #error_explanation
      .alert.alert-danger
        = pluralize(obj.errors.count, 'error')
        | &nbsp;prohibited this &nbsp;
        = obj.class.to_s.titleize
        | &nbsp; from being saved
      ul
        - obj.errors.full_messages.each do |msg|
          li = msg

app/views/common/_menu.slim
- custom_month_view_highlight  = params[:controller].eql?('expenditures') && params[:action].eql?('month_views') ? {status: :active} : {}
- custom_year_glance_highlight = params[:controller].eql?('expenditures') && params[:action].eql?('year_glance') ? {status: :active} : {}
- custom_my_secret_highlight   = params[:controller].eql?('secrets') && params[:action].eql?('manage_values') ? {status: :active} : {}
= nav_bar static: :top, brand: 'Home Account Manager', responsive: true, brand_link: expenditures_path, inverse: true do
  = menu_group do
    = menu_item 'Home', expenditures_path
    - current_time = Time.zone.now
    = menu_item 'Month View', month_views_path(month: current_time.month, year: current_time.year), custom_month_view_highlight
    = menu_item 'Year Glance', year_glance_path(year: current_time.year), custom_year_glance_highlight
    = menu_item 'Manage Defaults', default_expenditures_path
    = menu_item 'My Secrets', secrets_path, custom_my_secret_highlight
  = menu_group pull: :right do
    - if user_signed_in?
      = content_tag(:span, current_user.email, { class: 'user-name' })
      = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'sign-out'